#!/usr/bin/env python3
"""Pack a board's factory SD directory into deterministic C++ data."""

from __future__ import annotations

import argparse
import binascii
import os
from pathlib import Path
import tempfile


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def collect_entries(root: Path):
    entries = []
    data = bytearray()

    for path in sorted(root.rglob("*"), key=lambda item: item.as_posix()):
        if path.is_symlink():
            raise ValueError(f"symbolic links are not supported: {path}")

        relative = "/" + path.relative_to(root).as_posix()
        if path.is_dir():
            entries.append((relative, 0, 0, 0, True))
        elif path.is_file():
            contents = path.read_bytes()
            offset = len(data)
            data.extend(contents)
            checksum = binascii.crc_hqx(contents, 0)
            entries.append((relative, offset, len(contents), checksum, False))
        else:
            raise ValueError(f"unsupported directory entry: {path}")

    return entries, data


def render(entries, data: bytearray) -> str:
    lines = [
        "// Generated by radio/util/pack_factory_sd.py. Do not edit.",
        '#include "factory_reset.h"',
        "",
        '// The .factory_sd output section remains in internal flash on H7.',
        '#define FACTORY_SD_SECTION __attribute__((section(".factory_sd"), used))',
        "",
        "const uint8_t factorySdData[] FACTORY_SD_SECTION = {",
    ]

    if data:
        for offset in range(0, len(data), 16):
            chunk = data[offset : offset + 16]
            lines.append("  " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    else:
        lines.append("  0x00,")
    lines.extend(["};", ""])

    for index, entry in enumerate(entries):
        lines.append(
            f"const char factorySdPath{index}[] FACTORY_SD_SECTION = {c_string(entry[0])};"
        )

    lines.extend(["", "const FactorySdEntry factorySdEntries[] FACTORY_SD_SECTION = {"])

    file_count = 0
    for index, (path, offset, size, checksum, is_directory) in enumerate(entries):
        kind = "FactorySdEntryType::Directory" if is_directory else "FactorySdEntryType::File"
        if not is_directory:
            file_count += 1
        lines.append(
            f"  {{factorySdPath{index}, {offset}u, {size}u, 0x{checksum:04x}u, {kind}}},"
        )

    lines.extend(
        [
            "};",
            "",
            f"const uint16_t factorySdEntryCount FACTORY_SD_SECTION = {len(entries)}u;",
            f"const uint16_t factorySdFileCount FACTORY_SD_SECTION = {file_count}u;",
            f"const uint32_t factorySdDataSize FACTORY_SD_SECTION = {len(data)}u;",
            "",
            "#undef FACTORY_SD_SECTION",
            "",
        ]
    )
    return "\n".join(lines)


def atomic_write(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(prefix=path.name + ".", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as output:
            output.write(contents)
        os.replace(temporary_name, path)
    except Exception:
        os.unlink(temporary_name)
        raise


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    root = args.input.resolve()
    if not root.is_dir():
        parser.error(f"factory SD directory does not exist: {root}")

    entries, data = collect_entries(root)
    if not any(not entry[4] for entry in entries):
        parser.error(f"factory SD directory contains no files: {root}")

    atomic_write(args.output, render(entries, data))


if __name__ == "__main__":
    main()
