/*
 * ModalAI M0196 / Helm hardware definitions.
 */

#pragma once

#include "helm_basic.h"

#define CPU_FREQ 400000000
#define AHB_FREQUENCY 200000000
#define PERI1_FREQUENCY 100000000
#define PERI2_FREQUENCY 100000000
#define TIMER_MULT_APB1 2
#define TIMER_MULT_APB2 2

#define ADC_KERNEL_FREQUENCY 100000000
#define ADC_FREQUENCY (ADC_KERNEL_FREQUENCY / 4)
#define SDMMC_KERNEL_FREQUENCY 200000000
#define USB_KERNEL_FREQUENCY 48000000
#define SPI123_KERNEL_FREQUENCY 100000000
#define SPI45_KERNEL_FREQUENCY 100000000
#define SPI6_KERNEL_FREQUENCY 100000000

#define TELEMETRY_EXTI_PRIO 0

// ADC1: four gimbal axes followed by four joystick axes.
#define ADC_SAMPTIME LL_ADC_SAMPLINGTIME_8CYCLES_5
#define ADC_CHANNEL_RTC_BAT LL_ADC_CHANNEL_VBAT
#define ADC_VREF_PREC2 330
#define ADC_MAIN ADC1
#define ADC_DMA DMA1
#define ADC_DMA_CHANNEL LL_DMAMUX1_REQ_ADC1
#define ADC_DMA_STREAM LL_DMA_STREAM_0
#define ADC_DMA_STREAM_IRQ DMA1_Stream0_IRQn
#define ADC_DMA_STREAM_IRQHandler DMA1_Stream0_IRQHandler

#define ADC_GPIO_PIN_STICK_LH LL_GPIO_PIN_0
#define ADC_CHANNEL_STICK_LH LL_ADC_CHANNEL_10
#define ADC_GPIO_PIN_STICK_LV LL_GPIO_PIN_1
#define ADC_CHANNEL_STICK_LV LL_ADC_CHANNEL_11
#define ADC_GPIO_PIN_STICK_RV LL_GPIO_PIN_5
#define ADC_CHANNEL_STICK_RV LL_ADC_CHANNEL_8
#define ADC_GPIO_PIN_STICK_RH LL_GPIO_PIN_5
#define ADC_CHANNEL_STICK_RH LL_ADC_CHANNEL_19

#ifdef SUPPORT_JOYSTICK
#define HARDWARE_POT1
#define ADC_GPIO_PIN_POT1 LL_GPIO_PIN_0
#define ADC_CHANNEL_POT1 LL_ADC_CHANNEL_16
#define HARDWARE_POT2
#define ADC_GPIO_PIN_POT2 LL_GPIO_PIN_1
#define ADC_CHANNEL_POT2 LL_ADC_CHANNEL_17
#define HARDWARE_POT3
#define ADC_GPIO_PIN_POT3 LL_GPIO_PIN_0
#define ADC_CHANNEL_POT3 LL_ADC_CHANNEL_9
#define HARDWARE_POT4
#define ADC_GPIO_PIN_POT4 LL_GPIO_PIN_1
#define ADC_CHANNEL_POT4 LL_ADC_CHANNEL_5

#define ADC_GPIOA_PINS (ADC_GPIO_PIN_STICK_RH | ADC_GPIO_PIN_POT1 | ADC_GPIO_PIN_POT2)
#define ADC_GPIOB_PINS (ADC_GPIO_PIN_POT3 | ADC_GPIO_PIN_POT4)
#define ADC_GPIOC_PINS (ADC_GPIO_PIN_STICK_LH | ADC_GPIO_PIN_STICK_LV | ADC_GPIO_PIN_STICK_RV)
#define ADC_DIRECTION {1, 1, 1, 1, 1, 1, 1, 1}

#else

#define ADC_GPIOA_PINS (ADC_GPIO_PIN_STICK_RH)
#define ADC_GPIOC_PINS (ADC_GPIO_PIN_STICK_LH | ADC_GPIO_PIN_STICK_LV | ADC_GPIO_PIN_STICK_RV)
#define ADC_DIRECTION {1, 1, 1, 1}

#endif

// Internal CRSF module: UART4 on PH13/PH14. Module power remains unmanaged
// until HELM_INTERNAL_MODULE_POWER_UNVERIFIED is replaced by verified macros.
#define INTMODULE_TX_GPIO GPIO_PIN(GPIOH, 13)
#define INTMODULE_RX_GPIO GPIO_PIN(GPIOH, 14)
#define INTMODULE_USART UART4
#define INTMODULE_USART_IRQHandler UART4_IRQHandler
#define INTMODULE_USART_IRQn UART4_IRQn
#define INTMODULE_BOOTCMD_DEFAULT 0
#define SPORT_MAX_BAUDRATE 400000

// External USB-C uses the full-speed core on PA11/PA12.
#define USB_GPIO_VBUS GPIO_PIN(GPIOA, 9)
#define USB_GPIO_DM GPIO_PIN(GPIOA, 11)
#define USB_GPIO_DP GPIO_PIN(GPIOA, 12)
#define USB_GPIO_AF GPIO_AF10

// Powertip PE12864WRF-055-H-Q (ST7567), connected in 4-line serial mode.
#define LCD_MOSI_GPIO GPIO_PIN(GPIOE, 6)
#define LCD_CLK_GPIO GPIO_PIN(GPIOE, 2)
#define LCD_A0_GPIO GPIO_PIN(GPIOE, 4)
#define LCD_NCS_GPIO GPIO_PIN(GPIOE, 3)
#define LCD_RST_GPIO GPIO_PIN(GPIOE, 5)
#define LCD_SPI SPI4
#define LCD_GPIO_AF GPIO_AF5
#define LCD_SPI_PRESCALER LL_SPI_BAUDRATEPRESCALER_DIV8
#define LCD_SPI_FREQUENCY (SPI45_KERNEL_FREQUENCY / 8)

// Native 6-o'clock orientation is the bring-up default. These are deliberately
// simple constants so the physical mounting can be corrected without touching
// the controller driver.
#define LCD_SEG_DIRECTION_COMMAND 0xA0
#define LCD_COM_DIRECTION_COMMAND 0xC8
#define LCD_COLUMN_OFFSET 0

// M0196 DMAMUX1 allocation:
//   DMA1 stream 0: ADC1 (active)
//   DMA1 stream 1: SPI2 RX / future IMU (reserved)
//   DMA1 stream 2: SPI2 TX / future IMU (reserved)
//   DMA1 streams 3-6: free
//   DMA1 stream 7: SPI4 TX / LCD (active)
// DMA2 remains free for future serial or I2C users. BDMA channels 0 and 1 are
// reserved for future SPI6 RX and TX respectively. SDMMC uses its internal DMA.
#define LCD_DMA DMA1
#define LCD_DMA_Stream DMA1_Stream7
#define LCD_DMA_Stream_Num LL_DMA_STREAM_7
#define LCD_DMA_Stream_IRQn DMA1_Stream7_IRQn
#define LCD_DMA_Stream_IRQHandler DMA1_Stream7_IRQHandler
#define LCD_DMA_FLAGS                                                        \
  (DMA_HIFCR_CTCIF7 | DMA_HIFCR_CHTIF7 | DMA_HIFCR_CTEIF7 |                \
   DMA_HIFCR_CDMEIF7 | DMA_HIFCR_CFEIF7)
#define LCD_DMA_STATUS_COMPLETE DMA_HISR_TCIF7
#define LCD_DMA_STATUS_ERRORS                                              \
  (DMA_HISR_TEIF7 | DMA_HISR_DMEIF7 | DMA_HISR_FEIF7)

// Backlight: TIM8 channel 3 on PI7.
#define BACKLIGHT_TIMER_FREQ (PERI2_FREQUENCY * TIMER_MULT_APB2)
#define BACKLIGHT_TIMER TIM8
#define BACKLIGHT_GPIO GPIO_PIN(GPIOI, 7)
#define BACKLIGHT_GPIO_AF GPIO_AF3
#define BACKLIGHT_CCMR2 (TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3M_2)
#define BACKLIGHT_CCER TIM_CCER_CC3E
#define BACKLIGHT_BDTR TIM_BDTR_MOE
#define BACKLIGHT_COUNTER_REGISTER BACKLIGHT_TIMER->CCR3

// Haptics: TIM4 channels 1-4 on PD12-PD15. EdgeTX exposes one haptic
// strength, which is mirrored to all four motor drivers.
#define HAPTIC_PWM
#define HAPTIC_CUSTOM_PER5MS
#define HAPTIC_TIMER TIM4
#define HAPTIC_TIMER_FREQ (PERI1_FREQUENCY * TIMER_MULT_APB1)
#define HAPTIC_GPIO_AF GPIO_AF2
#define HAPTIC_CCMR1                                                       \
  (TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC2M_1 |              \
   TIM_CCMR1_OC2M_2)
#define HAPTIC_CCMR2                                                       \
  (TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3M_2 | TIM_CCMR2_OC4M_1 |              \
   TIM_CCMR2_OC4M_2)
#define HAPTIC_CCER                                                        \
  (TIM_CCER_CC1E | TIM_CCER_CC2E | TIM_CCER_CC3E | TIM_CCER_CC4E)

// RGB status LED: TIM5 channels 1-3 on PH10-PH12.
#define STATUS_LEDS
#define RGB_LED_TIMER TIM5
#define RGB_LED_TIMER_FREQ (PERI1_FREQUENCY * TIMER_MULT_APB1)
#define RGB_LED_BLUE_GPIO GPIO_PIN(GPIOH, 10)
#define RGB_LED_RED_GPIO GPIO_PIN(GPIOH, 11)
#define RGB_LED_GREEN_GPIO GPIO_PIN(GPIOH, 12)
#define RGB_LED_GPIO_AF GPIO_AF2

// SDMMC1, four-bit bus.
#define STORAGE_USE_SDIO
#define SD_PRESENT_GPIO GPIO_PIN(GPIOA, 8)
#define SD_SDIO_TRANSFER_CLK_DIV SDMMC_NSPEED_CLK_DIV
#define SD_SDIO_PIN_D0 GPIO_PIN(GPIOC, 8)
#define SD_SDIO_AF_D0 GPIO_AF12
#define SD_SDIO_PIN_D1 GPIO_PIN(GPIOC, 9)
#define SD_SDIO_AF_D1 GPIO_AF12
#define SD_SDIO_PIN_D2 GPIO_PIN(GPIOC, 10)
#define SD_SDIO_AF_D2 GPIO_AF12
#define SD_SDIO_PIN_D3 GPIO_PIN(GPIOC, 11)
#define SD_SDIO_AF_D3 GPIO_AF12
#define SD_SDIO_PIN_CMD GPIO_PIN(GPIOD, 2)
#define SD_SDIO_AF_CMD GPIO_AF12
#define SD_SDIO_PIN_CLK GPIO_PIN(GPIOC, 12)
#define SD_SDIO_AF_CLK GPIO_AF12
#define SD_SDIO SDMMC1

// I2C buses are reserved for future device-specific power drivers.
#define HELM_POWER_MONITOR_I2C I2C1
#define HELM_POWER_MONITOR_SCL_GPIO GPIO_PIN(GPIOB, 8)
#define HELM_POWER_MONITOR_SDA_GPIO GPIO_PIN(GPIOB, 9)
#define HELM_BATTERY_I2C I2C2
#define HELM_BATTERY_SCL_GPIO GPIO_PIN(GPIOB, 10)
#define HELM_BATTERY_SDA_GPIO GPIO_PIN(GPIOB, 11)

#define MS_TIMER TIM14
#define MS_TIMER_IRQn TIM8_TRG_COM_TIM14_IRQn
#define MS_TIMER_IRQHandler TIM8_TRG_COM_TIM14_IRQHandler

#define MIXER_SCHEDULER_TIMER TIM12
#define MIXER_SCHEDULER_TIMER_FREQ (PERI1_FREQUENCY * TIMER_MULT_APB1)
#define MIXER_SCHEDULER_TIMER_IRQn TIM8_BRK_TIM12_IRQn
#define MIXER_SCHEDULER_TIMER_IRQHandler TIM8_BRK_TIM12_IRQHandler
