/*
 * ModalAI M0196 schematic pin catalog.
 *
 * This file describes revision A, variant -2_VRX, dated 2026-07-28. Feature
 * definitions control which optional input sources the hardware generator can
 * use. Peripheral pin definitions remain inert until hal.h exports them to a
 * driver.
 */

#pragma once

// External USB-C: USB_OTG_FS.
#define HELM_EXTERNAL_USB_VBUS_GPIO GPIO_PIN(GPIOA, 9)
#define HELM_EXTERNAL_USB_DM_GPIO GPIO_PIN(GPIOA, 11)
#define HELM_EXTERNAL_USB_DP_GPIO GPIO_PIN(GPIOA, 12)
#define HELM_EXTERNAL_USB_GPIO_AF GPIO_AF10

// Powertip PE12864WRF-055-H-Q_005 LCD: SPI4.
#define HELM_LCD_SCK_GPIO GPIO_PIN(GPIOE, 2)
#define HELM_LCD_CS_GPIO GPIO_PIN(GPIOE, 3)
#define HELM_LCD_A0_GPIO GPIO_PIN(GPIOE, 4)
#define HELM_LCD_RESET_GPIO GPIO_PIN(GPIOE, 5)
#define HELM_LCD_MOSI_GPIO GPIO_PIN(GPIOE, 6)
#define HELM_LCD_GPIO_AF GPIO_AF5

// LCD backlight: TIM8 channel 3.
#define HELM_BACKLIGHT_GPIO GPIO_PIN(GPIOI, 7)
#define HELM_BACKLIGHT_GPIO_AF GPIO_AF3

// Soft-power latch.
#define HELM_POWER_BUTTON_GPIO GPIO_PIN(GPIOI, 5)
#define HELM_POWER_HOLD_GPIO GPIO_PIN(GPIOI, 6)

// SDMMC1 four-bit bus.
#define HELM_SD_DETECT_GPIO GPIO_PIN(GPIOA, 8)
#define HELM_SD_D0_GPIO GPIO_PIN(GPIOC, 8)
#define HELM_SD_D1_GPIO GPIO_PIN(GPIOC, 9)
#define HELM_SD_D2_GPIO GPIO_PIN(GPIOC, 10)
#define HELM_SD_D3_GPIO GPIO_PIN(GPIOC, 11)
#define HELM_SD_CLOCK_GPIO GPIO_PIN(GPIOC, 12)
#define HELM_SD_COMMAND_GPIO GPIO_PIN(GPIOD, 2)
#define HELM_SD_GPIO_AF GPIO_AF12

// RGB status LED: active-low TIM5 channels 1-3.
#define HELM_RGB_BLUE_GPIO GPIO_PIN(GPIOH, 10)
#define HELM_RGB_RED_GPIO GPIO_PIN(GPIOH, 11)
#define HELM_RGB_GREEN_GPIO GPIO_PIN(GPIOH, 12)
#define HELM_RGB_GPIO_AF GPIO_AF2

// Fan: open-drain TIM5 channel 4 with an external pull-up.
#define HELM_FAN_GPIO GPIO_PIN(GPIOI, 0)
#define HELM_FAN_GPIO_AF GPIO_AF2

// Haptic motors: TIM4 channels 1-4.
#define HELM_HAPTIC_LEFT_TOP_GPIO GPIO_PIN(GPIOD, 12)
#define HELM_HAPTIC_LEFT_BOTTOM_GPIO GPIO_PIN(GPIOD, 13)
#define HELM_HAPTIC_RIGHT_TOP_GPIO GPIO_PIN(GPIOD, 14)
#define HELM_HAPTIC_RIGHT_BOTTOM_GPIO GPIO_PIN(GPIOD, 15)
#define HELM_HAPTIC_GPIO_AF GPIO_AF2

// I2C1: onboard INA231 and spare expansion bus.
#define HELM_I2C1_SCL_GPIO GPIO_PIN(GPIOB, 8)
#define HELM_I2C1_SDA_GPIO GPIO_PIN(GPIOB, 9)
#define HELM_I2C1_GPIO_AF GPIO_AF4

// I2C2: battery-board SMBus.
#define HELM_I2C2_SCL_GPIO GPIO_PIN(GPIOB, 10)
#define HELM_I2C2_SDA_GPIO GPIO_PIN(GPIOB, 11)
#define HELM_I2C2_GPIO_AF GPIO_AF4
#define HELM_BATTERY_SHUTDOWN_GPIO GPIO_PIN(GPIOC, 2)
#define HELM_BATTERY_IRQ_GPIO GPIO_PIN(GPIOH, 4)

// I2C3: digital gimbals and the Hall sensor.
#define HELM_I2C3_SCL_GPIO GPIO_PIN(GPIOH, 7)
#define HELM_I2C3_SDA_GPIO GPIO_PIN(GPIOH, 8)
#define HELM_I2C3_GPIO_AF GPIO_AF4
#define HELM_GIMBAL_RIGHT_IRQ_GPIO GPIO_PIN(GPIOA, 6)
#define HELM_GIMBAL_LEFT_IRQ_GPIO GPIO_PIN(GPIOE, 7)

// Onboard 93AA66 EEPROM: SPI6.
#define HELM_EEPROM_MISO_GPIO GPIO_PIN(GPIOG, 12)
#define HELM_EEPROM_SCK_GPIO GPIO_PIN(GPIOG, 13)
#define HELM_EEPROM_MOSI_GPIO GPIO_PIN(GPIOG, 14)
#define HELM_EEPROM_CS_GPIO GPIO_PIN(GPIOG, 15)
#define HELM_EEPROM_GPIO_AF GPIO_AF5

// Expansion port power and serial interfaces.
#define HELM_EXPANSION_POWER_ENABLE_GPIO GPIO_PIN(GPIOH, 15)
#define HELM_EXPANSION_POWER_GOOD_GPIO GPIO_PIN(GPIOB, 5)
#define HELM_EXPANSION_UART1_TX_GPIO GPIO_PIN(GPIOB, 6)
#define HELM_EXPANSION_UART1_RX_GPIO GPIO_PIN(GPIOB, 7)
#define HELM_EXPANSION_UART1_GPIO_AF GPIO_AF7
#define HELM_EXPANSION_UART8_RX_GPIO GPIO_PIN(GPIOE, 0)
#define HELM_EXPANSION_UART8_TX_GPIO GPIO_PIN(GPIOE, 1)
#define HELM_EXPANSION_UART8_GPIO_AF GPIO_AF8

// Internal radio. PB12 and PB13 follow MCU direction, not the swapped net names.
#define HELM_INTERNAL_RADIO_UART4_TX_GPIO GPIO_PIN(GPIOH, 13)
#define HELM_INTERNAL_RADIO_UART4_RX_GPIO GPIO_PIN(GPIOH, 14)
#define HELM_INTERNAL_RADIO_UART4_GPIO_AF GPIO_AF8
#define HELM_INTERNAL_RADIO_UART5_RX_GPIO GPIO_PIN(GPIOB, 12)
#define HELM_INTERNAL_RADIO_UART5_TX_GPIO GPIO_PIN(GPIOB, 13)
#define HELM_INTERNAL_RADIO_UART5_GPIO_AF GPIO_AF14
#define HELM_INTERNAL_RADIO_USB_DM_GPIO GPIO_PIN(GPIOB, 14)
#define HELM_INTERNAL_RADIO_USB_DP_GPIO GPIO_PIN(GPIOB, 15)
#define HELM_INTERNAL_RADIO_USB_GPIO_AF GPIO_AF12
#define HELM_INTERNAL_RADIO_IRQ_GPIO GPIO_PIN(GPIOI, 4)
#define HELM_INTERNAL_RADIO_TEMP_GPIO GPIO_PIN(GPIOE, 8)
#define HELM_INTERNAL_RADIO_VBUS_ENABLE_GPIO GPIO_PIN(GPIOG, 7)

// Trainer port: USART6.
#define HELM_TRAINER_TX_GPIO GPIO_PIN(GPIOC, 6)
#define HELM_TRAINER_RX_GPIO GPIO_PIN(GPIOC, 7)
#define HELM_TRAINER_GPIO_AF GPIO_AF7
#define HELM_TRAINER_DIRECTION_GPIO GPIO_PIN(GPIOI, 8)

// Internal VRX: USART2.
#define HELM_VRX_TX_GPIO GPIO_PIN(GPIOD, 5)
#define HELM_VRX_RX_GPIO GPIO_PIN(GPIOD, 6)
#define HELM_VRX_GPIO_AF GPIO_AF7
#define HELM_VRX_POWER_ENABLE_GPIO GPIO_PIN(GPIOD, 7)

// Spare SPI5 expansion port.
#define HELM_SPI5_CS_GPIO GPIO_PIN(GPIOC, 13)
#define HELM_SPI5_SCK_GPIO GPIO_PIN(GPIOF, 7)
#define HELM_SPI5_MISO_GPIO GPIO_PIN(GPIOF, 8)
#define HELM_SPI5_MOSI_GPIO GPIO_PIN(GPIOF, 9)
#define HELM_SPI5_GPIO_AF GPIO_AF5

// Onboard BMI270 IMU: SPI2.
#define HELM_IMU_CS_GPIO GPIO_PIN(GPIOA, 10)
#define HELM_IMU_SCK_GPIO GPIO_PIN(GPIOI, 1)
#define HELM_IMU_MISO_GPIO GPIO_PIN(GPIOI, 2)
#define HELM_IMU_MOSI_GPIO GPIO_PIN(GPIOI, 3)
#define HELM_IMU_GPIO_AF GPIO_AF5
#define HELM_IMU_IRQ_GPIO GPIO_PIN(GPIOG, 2)
#define HELM_IMU_SYNC_IRQ_GPIO GPIO_PIN(GPIOG, 3)

// Analog gimbals: ADC1.
#if defined(HELM_HAS_ANALOG_GIMBALS)
  #define HELM_INPUT_GIMBAL_LH_GPIO GPIOC
  #define HELM_INPUT_GIMBAL_LH_PIN LL_GPIO_PIN_0
  #define HELM_INPUT_GIMBAL_LH_ADC ADC1
  #define HELM_INPUT_GIMBAL_LH_CHANNEL LL_ADC_CHANNEL_10
  #define HELM_INPUT_GIMBAL_LV_GPIO GPIOC
  #define HELM_INPUT_GIMBAL_LV_PIN LL_GPIO_PIN_1
  #define HELM_INPUT_GIMBAL_LV_ADC ADC1
  #define HELM_INPUT_GIMBAL_LV_CHANNEL LL_ADC_CHANNEL_11
  #define HELM_INPUT_GIMBAL_RV_GPIO GPIOC
  #define HELM_INPUT_GIMBAL_RV_PIN LL_GPIO_PIN_5
  #define HELM_INPUT_GIMBAL_RV_ADC ADC1
  #define HELM_INPUT_GIMBAL_RV_CHANNEL LL_ADC_CHANNEL_8
  #define HELM_INPUT_GIMBAL_RH_GPIO GPIOA
  #define HELM_INPUT_GIMBAL_RH_PIN LL_GPIO_PIN_5
  #define HELM_INPUT_GIMBAL_RH_ADC ADC1
  #define HELM_INPUT_GIMBAL_RH_CHANNEL LL_ADC_CHANNEL_19
#endif

// Analog joysticks and their push buttons.
#if defined(HELM_HAS_ANALOG_JOYSTICKS)
  #define HELM_INPUT_JOYSTICK_LH_GPIO GPIOA
  #define HELM_INPUT_JOYSTICK_LH_PIN LL_GPIO_PIN_0
  #define HELM_INPUT_JOYSTICK_LH_ADC ADC1
  #define HELM_INPUT_JOYSTICK_LH_CHANNEL LL_ADC_CHANNEL_16
  #define HELM_INPUT_JOYSTICK_LV_GPIO GPIOA
  #define HELM_INPUT_JOYSTICK_LV_PIN LL_GPIO_PIN_1
  #define HELM_INPUT_JOYSTICK_LV_ADC ADC1
  #define HELM_INPUT_JOYSTICK_LV_CHANNEL LL_ADC_CHANNEL_17
  #define HELM_INPUT_JOYSTICK_RV_GPIO GPIOB
  #define HELM_INPUT_JOYSTICK_RV_PIN LL_GPIO_PIN_0
  #define HELM_INPUT_JOYSTICK_RV_ADC ADC1
  #define HELM_INPUT_JOYSTICK_RV_CHANNEL LL_ADC_CHANNEL_9
  #define HELM_INPUT_JOYSTICK_RH_GPIO GPIOB
  #define HELM_INPUT_JOYSTICK_RH_PIN LL_GPIO_PIN_1
  #define HELM_INPUT_JOYSTICK_RH_ADC ADC1
  #define HELM_INPUT_JOYSTICK_RH_CHANNEL LL_ADC_CHANNEL_5
  #define HELM_INPUT_JOYSTICK_RIGHT_BUTTON_GPIO GPIOA
  #define HELM_INPUT_JOYSTICK_RIGHT_BUTTON_PIN LL_GPIO_PIN_7
  #define HELM_INPUT_JOYSTICK_LEFT_BUTTON_GPIO GPIOD
  #define HELM_INPUT_JOYSTICK_LEFT_BUTTON_PIN LL_GPIO_PIN_1
#endif

// Right board switches. Analog stuffing uses only the A net.
#if defined(HELM_HAS_BS_R1)
  #if defined(HELM_BS_R1_ANALOG)
    #define HELM_INPUT_BS_R1_ANALOG_GPIO GPIOA
    #define HELM_INPUT_BS_R1_ANALOG_PIN LL_GPIO_PIN_3
    #define HELM_INPUT_BS_R1_ANALOG_ADC ADC1
    #define HELM_INPUT_BS_R1_ANALOG_CHANNEL LL_ADC_CHANNEL_15
  #else
    #define HELM_INPUT_BS_R1_A_GPIO GPIOA
    #define HELM_INPUT_BS_R1_A_PIN LL_GPIO_PIN_3
    #define HELM_INPUT_BS_R1_B_GPIO GPIOA
    #define HELM_INPUT_BS_R1_B_PIN LL_GPIO_PIN_2
  #endif
#endif

#if defined(HELM_HAS_BS_R2)
  #if defined(HELM_BS_R2_ANALOG)
    #define HELM_INPUT_BS_R2_ANALOG_GPIO GPIOA
    #define HELM_INPUT_BS_R2_ANALOG_PIN LL_GPIO_PIN_4
    #define HELM_INPUT_BS_R2_ANALOG_ADC ADC1
    #define HELM_INPUT_BS_R2_ANALOG_CHANNEL LL_ADC_CHANNEL_18
  #else
    #define HELM_INPUT_BS_R2_A_GPIO GPIOA
    #define HELM_INPUT_BS_R2_A_PIN LL_GPIO_PIN_4
    #define HELM_INPUT_BS_R2_B_GPIO GPIOC
    #define HELM_INPUT_BS_R2_B_PIN LL_GPIO_PIN_3
  #endif
#endif

#if defined(HELM_HAS_BS_R3)
  #if defined(HELM_BS_R3_ANALOG)
    #define HELM_INPUT_BS_R3_ANALOG_GPIO GPIOC
    #define HELM_INPUT_BS_R3_ANALOG_PIN LL_GPIO_PIN_4
    #define HELM_INPUT_BS_R3_ANALOG_ADC ADC1
    #define HELM_INPUT_BS_R3_ANALOG_CHANNEL LL_ADC_CHANNEL_4
  #else
    #define HELM_INPUT_BS_R3_A_GPIO GPIOC
    #define HELM_INPUT_BS_R3_A_PIN LL_GPIO_PIN_4
    #define HELM_INPUT_BS_R3_B_GPIO GPIOB
    #define HELM_INPUT_BS_R3_B_PIN LL_GPIO_PIN_2
  #endif
#endif

#if defined(HELM_HAS_BS_R4)
  #define HELM_INPUT_BS_R4_A_GPIO GPIOF
  #define HELM_INPUT_BS_R4_A_PIN LL_GPIO_PIN_12
  #define HELM_INPUT_BS_R4_B_GPIO GPIOF
  #define HELM_INPUT_BS_R4_B_PIN LL_GPIO_PIN_15
#endif

#if defined(HELM_HAS_BS_R5)
  #define HELM_INPUT_BS_R5_A_GPIO GPIOF
  #define HELM_INPUT_BS_R5_A_PIN LL_GPIO_PIN_11
  #define HELM_INPUT_BS_R5_B_GPIO GPIOF
  #define HELM_INPUT_BS_R5_B_PIN LL_GPIO_PIN_14
#endif

// Left board switches. Analog stuffing uses only the A net.
#if defined(HELM_HAS_BS_L1)
  #if defined(HELM_BS_L1_ANALOG)
    #define HELM_INPUT_BS_L1_ANALOG_GPIO GPIOF
    #define HELM_INPUT_BS_L1_ANALOG_PIN LL_GPIO_PIN_10
    #define HELM_INPUT_BS_L1_ANALOG_ADC ADC3
    #define HELM_INPUT_BS_L1_ANALOG_CHANNEL LL_ADC_CHANNEL_6
  #else
    #define HELM_INPUT_BS_L1_A_GPIO GPIOF
    #define HELM_INPUT_BS_L1_A_PIN LL_GPIO_PIN_10
    #define HELM_INPUT_BS_L1_B_GPIO GPIOG
    #define HELM_INPUT_BS_L1_B_PIN LL_GPIO_PIN_4
  #endif
#endif

#if defined(HELM_HAS_BS_L2)
  #if defined(HELM_BS_L2_ANALOG)
    #define HELM_INPUT_BS_L2_ANALOG_GPIO GPIOF
    #define HELM_INPUT_BS_L2_ANALOG_PIN LL_GPIO_PIN_3
    #define HELM_INPUT_BS_L2_ANALOG_ADC ADC3
    #define HELM_INPUT_BS_L2_ANALOG_CHANNEL LL_ADC_CHANNEL_5
  #else
    #define HELM_INPUT_BS_L2_A_GPIO GPIOF
    #define HELM_INPUT_BS_L2_A_PIN LL_GPIO_PIN_3
    #define HELM_INPUT_BS_L2_B_GPIO GPIOG
    #define HELM_INPUT_BS_L2_B_PIN LL_GPIO_PIN_5
  #endif
#endif

#if defined(HELM_HAS_BS_L3)
  #if defined(HELM_BS_L3_ANALOG)
    #define HELM_INPUT_BS_L3_ANALOG_GPIO GPIOF
    #define HELM_INPUT_BS_L3_ANALOG_PIN LL_GPIO_PIN_4
    #define HELM_INPUT_BS_L3_ANALOG_ADC ADC3
    #define HELM_INPUT_BS_L3_ANALOG_CHANNEL LL_ADC_CHANNEL_9
  #else
    #define HELM_INPUT_BS_L3_A_GPIO GPIOF
    #define HELM_INPUT_BS_L3_A_PIN LL_GPIO_PIN_4
    #define HELM_INPUT_BS_L3_B_GPIO GPIOG
    #define HELM_INPUT_BS_L3_B_PIN LL_GPIO_PIN_6
  #endif
#endif

#if defined(HELM_HAS_BS_L4)
  #define HELM_INPUT_BS_L4_A_GPIO GPIOH
  #define HELM_INPUT_BS_L4_A_PIN LL_GPIO_PIN_6
  #define HELM_INPUT_BS_L4_B_GPIO GPIOE
  #define HELM_INPUT_BS_L4_B_PIN LL_GPIO_PIN_13
#endif

#if defined(HELM_HAS_BS_L5)
  #define HELM_INPUT_BS_L5_A_GPIO GPIOE
  #define HELM_INPUT_BS_L5_A_PIN LL_GPIO_PIN_15
  #define HELM_INPUT_BS_L5_B_GPIO GPIOG
  #define HELM_INPUT_BS_L5_B_PIN LL_GPIO_PIN_8
#endif

// Upper-left five-way switch.
#if defined(HELM_HAS_FIVE_WAY_UPPER_LEFT)
  #define HELM_INPUT_UPR_L_A_GPIO GPIOD
  #define HELM_INPUT_UPR_L_A_PIN LL_GPIO_PIN_8
  #define HELM_INPUT_UPR_L_B_GPIO GPIOD
  #define HELM_INPUT_UPR_L_B_PIN LL_GPIO_PIN_9
  #define HELM_INPUT_UPR_L_C_GPIO GPIOD
  #define HELM_INPUT_UPR_L_C_PIN LL_GPIO_PIN_10
  #define HELM_INPUT_UPR_L_D_GPIO GPIOD
  #define HELM_INPUT_UPR_L_D_PIN LL_GPIO_PIN_11
  #define HELM_INPUT_UPR_L_E_GPIO GPIOH
  #define HELM_INPUT_UPR_L_E_PIN LL_GPIO_PIN_9
#endif

// Upper-right five-way switch.
#if defined(HELM_HAS_FIVE_WAY_UPPER_RIGHT)
  #define HELM_INPUT_UPR_R_A_GPIO GPIOG
  #define HELM_INPUT_UPR_R_A_PIN LL_GPIO_PIN_11
  #define HELM_INPUT_UPR_R_B_GPIO GPIOG
  #define HELM_INPUT_UPR_R_B_PIN LL_GPIO_PIN_10
  #define HELM_INPUT_UPR_R_C_GPIO GPIOD
  #define HELM_INPUT_UPR_R_C_PIN LL_GPIO_PIN_3
  #define HELM_INPUT_UPR_R_D_GPIO GPIOD
  #define HELM_INPUT_UPR_R_D_PIN LL_GPIO_PIN_4
  #define HELM_INPUT_UPR_R_E_GPIO GPIOG
  #define HELM_INPUT_UPR_R_E_PIN LL_GPIO_PIN_9
#endif

// Lower-left five-way switch.
#if defined(HELM_HAS_FIVE_WAY_LOWER_LEFT)
  #define HELM_INPUT_LOW_L_A_GPIO GPIOG
  #define HELM_INPUT_LOW_L_A_PIN LL_GPIO_PIN_0
  #define HELM_INPUT_LOW_L_B_GPIO GPIOG
  #define HELM_INPUT_LOW_L_B_PIN LL_GPIO_PIN_1
  #define HELM_INPUT_LOW_L_C_GPIO GPIOF
  #define HELM_INPUT_LOW_L_C_PIN LL_GPIO_PIN_13
  #define HELM_INPUT_LOW_L_D_GPIO GPIOF
  #define HELM_INPUT_LOW_L_D_PIN LL_GPIO_PIN_6
  #define HELM_INPUT_LOW_L_E_GPIO GPIOF
  #define HELM_INPUT_LOW_L_E_PIN LL_GPIO_PIN_2
#endif

// Lower-right five-way switch.
#if defined(HELM_HAS_FIVE_WAY_LOWER_RIGHT)
  #define HELM_INPUT_LOW_R_A_GPIO GPIOF
  #define HELM_INPUT_LOW_R_A_PIN LL_GPIO_PIN_5
  #define HELM_INPUT_LOW_R_B_GPIO GPIOH
  #define HELM_INPUT_LOW_R_B_PIN LL_GPIO_PIN_5
  #define HELM_INPUT_LOW_R_C_GPIO GPIOI
  #define HELM_INPUT_LOW_R_C_PIN LL_GPIO_PIN_9
  #define HELM_INPUT_LOW_R_D_GPIO GPIOI
  #define HELM_INPUT_LOW_R_D_PIN LL_GPIO_PIN_10
  #define HELM_INPUT_LOW_R_E_GPIO GPIOI
  #define HELM_INPUT_LOW_R_E_PIN LL_GPIO_PIN_11
#endif

// Quick-menu buttons.
#if defined(HELM_HAS_QUICK_BUTTONS)
  #define HELM_INPUT_MENU_1_GPIO GPIOE
  #define HELM_INPUT_MENU_1_PIN LL_GPIO_PIN_9
  #define HELM_INPUT_MENU_2_GPIO GPIOE
  #define HELM_INPUT_MENU_2_PIN LL_GPIO_PIN_10
  #define HELM_INPUT_MENU_3_GPIO GPIOE
  #define HELM_INPUT_MENU_3_PIN LL_GPIO_PIN_11
  #define HELM_INPUT_MENU_4_GPIO GPIOE
  #define HELM_INPUT_MENU_4_PIN LL_GPIO_PIN_12
  #define HELM_INPUT_MENU_5_GPIO GPIOE
  #define HELM_INPUT_MENU_5_PIN LL_GPIO_PIN_14
#endif

// VRX buttons.
#if defined(HELM_HAS_VRX_BUTTONS)
  #define HELM_INPUT_VRX_1_GPIO GPIOF
  #define HELM_INPUT_VRX_1_PIN LL_GPIO_PIN_0
  #define HELM_INPUT_VRX_2_GPIO GPIOF
  #define HELM_INPUT_VRX_2_PIN LL_GPIO_PIN_1
  #define HELM_INPUT_VRX_3_GPIO GPIOH
  #define HELM_INPUT_VRX_3_PIN LL_GPIO_PIN_3
  #define HELM_INPUT_VRX_4_GPIO GPIOH
  #define HELM_INPUT_VRX_4_PIN LL_GPIO_PIN_2
#endif

// Hall sensor interrupt. The sensor data path uses I2C3.
#if defined(HELM_HAS_HALL_SENSOR)
  #define HELM_INPUT_HALL_INT_GPIO GPIOD
  #define HELM_INPUT_HALL_INT_PIN LL_GPIO_PIN_0
#endif
